# Generated by Django 5.1.3 on 2025-11-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('event_type', models.CharField(choices=[('product.created', 'Product Created'), ('product.updated', 'Product Updated'), ('product.deleted', 'Product Deleted')], db_index=True, max_length=50)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'webhooks',
                'indexes': [models.Index(fields=['event_type', 'enabled'], name='webhooks_event_t_f85b11_idx'), models.Index(fields=['enabled'], name='webhooks_enabled_3de2d1_idx')],
            },
        ),
    ]
