# Generated by Django 5.1.3 on 2025-11-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_importjob_celery_task_id_importjob_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importjob',
            name='phase',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('parsing', 'Parsing'), ('processing', 'Processing'), ('completed', 'Completed')], db_index=True, default='uploading', max_length=20),
        ),
        migrations.AddField(
            model_name='importjob',
            name='s3_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
